name: sm_network
description: "A Flutter networking library that provides a simple and convenient
  way to access network resources."
version: 0.0.6
homepage: "https://github.com/shay-wong/flutter_sm_network"
repository: "https://github.com/shay-wong/flutter_sm_network"
issue_tracker: "https://github.com/shay-wong/flutter_sm_network/issues"

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  convert: ^3.1.1
  cross_file: ^0.3.3
  crypto: ^3.0.3
  dio: ^5.4.3
  dio_cache_interceptor: ^3.5.0
  json_annotation: ^4.8.1
  sm_logger: ^0.0.7
  sm_models: ^0.0.4
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
